### ISSUE TITLE
Javascript comment-dwim

### ISSUE THREAD

**Issue by stevemolitor** [fxbois/web-mode#447]
The JS comment syntax is ```'/* */'``` in web-mode but it is ```//``` in js-mode, js2-mode, etc.  Using the block comment syntax is a problem because you can't comment out a region that already has a block comment (i.e. for JS doc).  Web-mode needs an option to use ```//``` comment style.

**Comment by fxbois** [comment]
@stevemolitor you can use ```(add-to-list 'web-mode-comment-formats '("javascript" . "//"))```

**Comment by stevemolitor** [comment]
Thanks for the quick response!.  I found two issues though:

Uncommenting regions doesn't work after adding `//` to `web-mode-comment-formats`.  For example I can select two lines, run `web-mode-comment-or-uncomment` lines and get this:

```javascript
// var x = 1;
// var y = 2;
```

But when I select those two lines as the region and run  `web-mode-comment-or-uncomment` again only the first line is uncommented and I get this:

```javascript
var x = 1;
// var y = 2;
```

Also adding to `web-mode-comment-formats` doesn't work for JSX, because of https://github.com/fxbois/web-mode/blob/master/web-mode.el#L7901.  Hacking that to add jsx fixed it:

```lisp
         ((member language '("php" "javascript" "java" "jsx"))
```

**Comment by fxbois** [comment]
@stevemolitor I've committed a new patch

**Comment by stevemolitor** [comment]
Thanks for the new fix.  Uncomment doesn't work - it only replaces the first matching '//'.  To fix it I had to change this:

https://github.com/fxbois/web-mode/blob/master/web-mode.el#L7976
```lisp
  (setq comment (replace-regexp-in-string "\\(^//\\)" "" comment)))
```

to this:

```lisp
  (setq comment (replace-regexp-in-string "//" "" comment)))
```

From the doc of replace-regexp-in-string:

```
To replace only the first match (if any), make REGEXP match up to \'
and replace a sub-expression, e.g.
  (replace-regexp-in-string "\\(foo\\).*\\'" "bar" " foo foo" nil nil 1)
    => " bar foo"
```

**Comment by stevemolitor** [comment]
Actually that doesn't work - it only uncomments the first two commented out lines of the selected region.  The issue in this case seems to be with ```web-mode-comment-boundaries```.  It only the returned range only includes the first two lines, 

For example try commenting and uncommenting the following JS with ```"//"``` as the comment syntax:

```javascript
    var x = 1;
    var y = 2;
    var z = 3;
```

It will comment out all three lines, but only uncomment the last line:

```javascdript
    var x = 1;
    var y = 2;
    // var z = 3;
```

**Comment by fxbois** [comment]
@stevemolitor I ve found a more deeper bug yesterday in the comment-or-uncomment function. I need to work on this. I'll keep you posted.

**Comment by stevemolitor** [comment]
@fxbois Ok great thanks! I love web-mode an pretty much use it 90% of the day for JS, css, html, jsx etc.

**Comment by fxbois** [comment]
@stevemolitor I've pushed a new version

**Comment by stevemolitor** [comment]
@fxbois I tried the new version but it still doesn't uncomment JS properly. It only uncomments two lines as in the example above.

I did this to set the comment syntax:

```lisp
  (add-to-list 'web-mode-comment-formats '("javascript" . "//" ))
```

But if I comment and uncomment 3 or more lines of JS it only uncomments the first two lines.

**Comment by fxbois** [comment]
@stevemolitor I hope this one is the good one

**Comment by stevemolitor** [comment]
:+1: This version works great!  Thanks a bunch.
