### ISSUE TITLE
Bad JS decorators indentation

### ISSUE THREAD

**Issue by vslinko** [fxbois/web-mode#510]
actual:
```
@decorator1()
  @decorator2()
  @decorator3()
  class Name {

  }
```

expected:
```
@decorator1()
@decorator2()
@decorator3()
class Name {

}
```

**Comment by vslinko** [comment]
I think problem is decorator is interpreted as function call without semicolon, but decorators can't be closed by semicolon.

**Comment by fxbois** [comment]
@vslinko I do not deal with statements without semilicons

**Comment by vslinko** [comment]
But decorators can't be used with semicolons. I don't know how do you parse code, but maybe that problem could be hacked using @ character?

**Comment by fxbois** [comment]
@vslinko do you have a pointer to the spec ?

**Comment by vslinko** [comment]
This is a draft feature, but you can find grammar here https://github.com/wycats/javascript-decorators/blob/master/README.md

**Comment by fxbois** [comment]
@vslinko the last commit should solve the issue

**Comment by vslinko** [comment]
No, problem is still here, try example from my first message.

**Comment by fxbois** [comment]
@vslinko I've submitted another patch

**Comment by vslinko** [comment]
Could you publish package to melpa?

**Comment by fxbois** [comment]
it is done automatically

**Comment by vslinko** [comment]
Another problem: 

actual:
```
@decorator({
a: 1
})
  class QWE {
  }
```

expected:
```
@decorator({
  a: 1
})
class QWE {
}
```

**Comment by fxbois** [comment]
@vslinko I thought decorators were on one line. I won't be able to deal with this

**Comment by vslinko** [comment]
So, could you rollback `@` indent hack, because previous indent pattern is better than current
