### ISSUE TITLE
JSP comments closing with incomplete ending

### ISSUE THREAD

**Issue by Archenoth** [fxbois/web-mode#620]
Sometimes I see people comment and uncomment blocks of JSP markup by surrounding it with `<%--  --%>`, and adding or removing a space to the top closing tag like so:

```JSP
Not commented
<%--  -- %>
Commented
<%--  --%>
Not commented again
```

In this case, "Commented" is commented out because of the space on the first line, but web-mode's JSP engine appears to think otherwise.

This is web-mode 20151018.1241 from MELPA (Commit 118055b73a3baff019857bdb984f44d88390e1ae) on Emacs 24.5.1.

**Comment by fxbois** [comment]
I'll look at this

**Comment by fxbois** [comment]
@Archenoth it is now solved with the last version on github

**Comment by Archenoth** [comment]
Ah, sweet... It's fixed when loading files..!

...but, when adding a space in an existing file, it still appears to break.

So, if you start with a buffer like above:
```JSP
<%--  --%>
Words
<%--  --%>
```
...and then you add a space at the end of the first tag like so:
```JSP
<%--  -- %>
Words
<%--  --%>
```

It doesn't recognize the top as a comment:
![screenshot from 2015-10-19 15 45 43](https://cloud.githubusercontent.com/assets/1385527/10592326/a646220c-7678-11e5-83a9-5c5005cc1669.png)

However this fixes itself if you edit the contents of the comment.

**Comment by fxbois** [comment]
I've looked at it and it would be quite difficult. I prefer not to touch to this part of web-mode which is very generic

**Comment by Archenoth** [comment]
Oh fun. Nothing quite like an abstraction limitation.

Since the title of this issue isn't exactly a problem any more, should we close this issue..? (And possibly open another for generic buffer updating?)

**Comment by fxbois** [comment]
@Archenoth yes oyu could open an other specific issue

**Comment by Archenoth** [comment]
Alright, I shall do that then.
