### ISSUE TITLE
web mode indentation (PHP and Dust)

### ISSUE THREAD

**Issue by molgrum** [fxbois/web-mode#786]
Hi.

When using web mode and editing Dust or PHP mixed with HTML the indentation is very buggy. Sometimes it is correct, other times it is not indenting any block at all. If writing .php and indenting mixed with HTML it is not indenting one step right after "<?php" but the rest of the code indents correctly. Dust is worse, when creating a template script it indents only one step (after "<script ...") so all the lines are on the same indentation level.

Just me that got this problem?

**Comment by fxbois** [comment]
@molgrum this kind of report is useless

**Comment by molgrum** [comment]
Here is an example of how Dust breaks for me:
[http://pastebin.com/CLh4an5U](http://pastebin.com/CLh4an5U)

Paste into Emacs + web mode and C-x h TAB

**Comment by fxbois** [comment]
@molgrum thank you, I'll look at this

**Comment by fxbois** [comment]
@molgrum I didn't know ```<script type="text/x-dust-template">```
I've just pushed a fix that should solve this issue

**Comment by molgrum** [comment]
I edited web-mode.el in elpa directory with this change, it is still the same problem. Does it work for you?
I just open that HTML file i pasted and indentation is the same.

**Comment by fxbois** [comment]
use the version available on github

**Comment by molgrum** [comment]
Got the update now and it works, thanks alot!
