### ISSUE TITLE
Angular html string indenting incorrectly

### ISSUE THREAD

**Issue by hlolli** [fxbois/web-mode#984]
I'm useing from melpa `webmode-20180326.451`

the indentation in Angular is strange
```js
@Component({
    template: `
        <div>
            <ul>
                <li>Suche</li>
                    <li>Suche</li>
                        <li>Suche</li>
            </ul>
        </div>
    `
})
```

the ul tags match, but the li tags keep getting nested.

ADDED:

```
@Component({
    template: `
        <div>
            <div>Suche</div>
                <div>Suche</div>
                    <div>Suche</div>
        </div>
    `
})
```
all 2nd level nesting wrong?

**Comment by fxbois** [comment]
@hlolli should be fixed with last commit

**Comment by hlolli** [comment]
Works, thanks!

**Comment by hlolli** [comment]
@fxbois I notice one indentation bug, less serious, but it seems that 1st level second sibling html block doesn't get indented like the first sibling, so given this code.
```html
    template: `
            <div>
            <div>Suche</div>
            <div>Suche</div>
            <div>Suche</div>
            </div>
            <div>
            <div>Suche</div>
            <div>Suche</div>
            <div>Suche</div>
           </div>
    `
```
I select it all and indent the region, I end with
```html
    template: `
        <div>
            <div>Suche</div>
            <div>Suche</div>
            <div>Suche</div>
        </div>
            <div>
                <div>Suche</div>
                <div>Suche</div>
                <div>Suche</div>
            </div>
    `,
```
I would have expected
```html
    template: `
        <div>
            <div>Suche</div>
            <div>Suche</div>
            <div>Suche</div>
        </div>
        <div>
            <div>Suche</div>
            <div>Suche</div>
            <div>Suche</div>
        </div>
    `,
```

**Comment by fxbois** [comment]
@hlolli new fix pushed

**Comment by hlolli** [comment]
I did update my melpa package package
```
  web-mode           20180405.513  installed             major mode for editing web templates
```
I still experience the exact same behaviour
```
@Component({
    template: `
               <div>
                <div>Suche</div>
                <div>Suche</div>
                <div>Suche</div>
                </div>
                <div>
                <div>Suche</div>
                <div>Suche</div>
                <div>Suche</div>
                </div>
    
    `})
```
Make region the this whole thing, press TAB (bound to indent on my computer) result:
```
@Component({
    template: `
        <div>
            <div>Suche</div>
            <div>Suche</div>
            <div>Suche</div>
        </div>
                <div>
                    <div>Suche</div>
                    <div>Suche</div>
                    <div>Suche</div>
                </div>
    
    `})
```

**Comment by fxbois** [comment]
@hlolli perhaps because I havent updated the package version
